name: test

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v3.0.14
      with: 
        # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
        repo-token: hallo
        # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
        stale-issue-message: hallo
        # The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.
        stale-pr-message: hallo
        # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
        close-issue-message: hallo
        # The message to post on the pr when closing it. If none provided, will not comment when closing a pull requests.
        close-pr-message: hallo
        # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
